//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quan_li_nha_hang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52d25171_6f47_4125_9411_b25539ebf3c9 {
            get {
                object obj = ResourceManager.GetObject("_52d25171_6f47_4125_9411_b25539ebf3c9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52d25171_6f47_4125_9411_b25539ebf3c9_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_52d25171_6f47_4125_9411_b25539ebf3c9_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c94793cf_13f3_481d_ba0d_ac7773a785b8 {
            get {
                object obj = ResourceManager.GetObject("c94793cf_13f3_481d_ba0d_ac7773a785b8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_png_of_Account_png_line_icon_user_symbol_by_Aew_about_profile_icon__person_icon__person_icon_png__profile_png__and_profile_3012376 {
            get {
                object obj = ResourceManager.GetObject("Download_premium_png_of_Account_png_line_icon_user_symbol_by_Aew_about_profile_ic" +
                        "on__person_icon__person_icon_png__profile_png__and_profile_3012376", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_png_of_Account_png_line_icon_user_symbol_by_Aew_about_profile_icon__person_icon__person_icon_png__profile_png__and_profile_3012376_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Download_premium_png_of_Account_png_line_icon_user_symbol_by_Aew_about_profile_ic" +
                        "on__person_icon__person_icon_png__profile_png__and_profile_3012376_removebg_prev" +
                        "iew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ikon_Pencarian__Cari_Clipart__Kaca_Pembesar__Cari_PNG_Transparan_Clipart_dan_File_PSD_untuk_Unduh_Gratis {
            get {
                object obj = ResourceManager.GetObject("Ikon_Pencarian__Cari_Clipart__Kaca_Pembesar__Cari_PNG_Transparan_Clipart_dan_File" +
                        "_PSD_untuk_Unduh_Gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ikon_Pencarian__Cari_Clipart__Kaca_Pembesar__Cari_PNG_Transparan_Clipart_dan_File_PSD_untuk_Unduh_Gratis_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Ikon_Pencarian__Cari_Clipart__Kaca_Pembesar__Cari_PNG_Transparan_Clipart_dan_File" +
                        "_PSD_untuk_Unduh_Gratis_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
